
name: Azure .NET Core Web App Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./HorasExtrasAppClean.csproj

      - name: Build
        run: dotnet build ./HorasExtrasAppClean.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./HorasExtrasAppClean.csproj --configuration Release --output ./publish_output --no-build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep to Azure
        run: |
          az deployment sub create             --location eastus             --template-file infra/main.bicep             --name deploy-horasextras-from-github
